services:
  gateway:
    build:
      context: gateway
    depends_on:
      - database
    restart: no
    environment:
      SERVER_PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:postgresql://database/hashtest-db
    ports:
      - "8080:8080"
  interpret:
    build:
      context: interpret
    depends_on:
      - database
      - gateway
    restart: no
    environment:
      SERVER_PORT: 8081
      SPRING_DATASOURCE_URL: jdbc:postgresql://database/hashtest-db
    ports:
      - "8081:8081"
  attack:
    build:
      context: attack
    depends_on:
      - database
      - gateway
    restart: no
    environment:
      SERVER_PORT: 8082
      SPRING_DATASOURCE_URL: jdbc:postgresql://database/hashtest-db
    ports:
      - "8082:8082"
  database:
    image: postgres:16
    restart: no
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: hashtest-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - database:/var/lib/postgresql/data
volumes:
  database: { }